export type EventType = 'SESSION_STARTED'|'SEARCH'|'CONTENT_VIEWED'|'FILTER_USED'|'RECOMMENDATION_SHOWN'|'RECOMMENDATION_CLICKED'|'ACTION_STARTED'|'ACTION_COMPLETED'|'SESSION_ENDED'|'NAVIGATION_BACK';
export type Content = { id:string; title:string; category:string; startTime:string; tags:string[]; popularity:number; status:'Live'|'Upcoming'; venue:string; description:string; accent:string };
export type SessionEvent = { id:string; sessionId:string; eventType:EventType; contentId?:string; metadata:Record<string,unknown>; createdAt:string };
export type SessionRole = 'EXPLORER'|'RESEARCHER'|'COMPARATOR'|'DECISION_READY';
export type Intent = { intent:string; category?:string; timeContext?:string; confidence:number; signals:string[]; role:SessionRole };
export type Friction = { detected:boolean; type:'navigation_loop'|'repeated_search'|'filter_confusion'|null; severity:'low'|'medium'|'high'; message:string };
export type Recommendation = { content:Content; score:number; reasons:string[]; explanation:string };
export type Session = { id:string; userId:string; startedAt:string; endedAt?:string; mode:'control'|'intelligent'; events:SessionEvent[]; intent:Intent; friction:Friction };
export type SessionMetrics = { totalSessions:number; sessionConversionRate:number; actionsPerSession:number; timeToFirstAction:number; finalStepConversion:number; valuePerSession:number; sessionsPerUser:number };
